### ISSUE TITLE
Launch game Directly

### ISSUE THREAD

**Issue by aPpYe** [XXXBold/PCSX2_MultiConfigTool#3]
Hey there!  Would it be possible for you to add some functionality to launch the game directly from within the GUI?  I realize it isn't supposed to be a frontend, but it is reasonably close if it just had a button like that.  Or perhaps double clicking the config in the config file manager?

**Comment by XXXBold** [comment]
Well, you can already launch PCSX2 with the desired configuration:
![Unbenannt](https://user-images.githubusercontent.com/30773753/145004084-2fff6f8a-828f-4aa3-a80c-b203ee57f84f.png)
You mean to also start PCSX2 when double-clicking an entry directly? That should be doable. 
Edit:
Ah, I see, there are issues with resizing the window, so the button is sometimes not visible. Will fix this.

**Comment by aPpYe** [comment]
Yes!  Thanks for replying.  I see you are running Cinnamon as well.  Fantastic!  Here's what the app looks like when I launch it:

![image](https://user-images.githubusercontent.com/41242127/145686185-5b2fc2b9-86e5-4d22-aefe-0ff0a4ccb92f.png)

Thanks for your time.

**Comment by XXXBold** [comment]
Fixed: https://github.com/XXXBold/PCSX2_MultiConfigTool/releases/tag/v0.7-beta
